version: '3.7'

services:
    postgres1:
        build: .
        volumes:
            - postgres1:/var/lib/data/postgres
            - ./postgres.conf:/etc/postgres.conf
            - ./schema.sql:/etc/schema.sql
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        secrets:
            - postgres_password
        ports:
            - '0:5432'
    postgres2:
        build: .
        volumes:
            - postgres2:/var/lib/data/postgres
            - ./postgres.conf:/etc/postgres.conf
            - ./schema.sql:/etc/schema.sql
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        secrets:
            - postgres_password
        ports:
            - '0:5432'

volumes:
    postgres1: ~
    postgres2: ~

secrets:
    postgres_password:
        file: postgres_password
